#ddev-generated
services:
  e2e-testing:
    container_name: ddev-${DDEV_SITENAME}-e2e-testing
    build:
      context: .
      dockerfile: Dockerfile.e2e
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    command: tail -f /dev/null
    working_dir: /var/www/html
    restart: "no"
    # These labels ensure this service is discoverable by DDEV.
    volumes:
      - "${DDEV_APPROOT}/e2e-testing:/var/www/html"
      - "/mnt/ddev-global-cache/mkcert:/mnt/ddev-global-cache/mkcert:ro"
    x-ddev:
      ssh-shell: bash
