#ddev-generated
services:
  e2e-testing:
    container_name: ddev-${DDEV_SITENAME}-e2e-testing
    build:
      context: .
      dockerfile: Dockerfile.e2e
    command: tail -f /dev/null
    restart: "no"
    # These labels ensure this service is discoverable by DDEV.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}

    volumes:
      - ".:/var/www/html"
