#ddev-generated
version: "3.6"

services:
  e2e-testing:
    container_name: ddev-${DDEV_SITENAME}-e2e-testing
    build:
      context: .
      dockerfile: Dockerfile.e2e
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    command: tail -f /dev/null
    working_dir: /var/www/html
    restart: "no"
    volumes:
      - "${DDEV_APPROOT}/e2e-testing:/var/www/html"

      # DDEV-global-cache (mkcert is here for all DDEV users)
      - ddev-global-cache:/mnt/ddev-global-cache

      # Your local mkcert folder (Linux example)
      - "${HOME}/.local/share/mkcert:/mkcert:ro"

      # (optional for macOS)
      # - "$HOME/Library/Application Support/mkcert:/mkcert-macos:ro"

    x-ddev:
      ssh-shell: bash

volumes:
  ddev-global-cache:
    external: true
